language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "nightly"
    - "pypy"
    - "pypy3"

install:
    - pip install nose
    - pip install -e .

script: nosetests -s
