name: run

on:
  push:
    branches:
    - main
    - ci
  pull_request:
    branches:
    - main


env:
  # query OSV for known malware before syncing
  UV_MALWARE_CHECK: "1"


jobs:
  tests-cpython:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, "3.10", "3.11", "3.12", "3.13", "3.14"]
    container:
      image: python:${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v10.0.1
      with:
        version: "latest-known"

    - name: Run test suite with CPython
      run: |
        uv venv --python python venv-test
        . venv-test/bin/activate
        uv pip install -e '.[testing]'
        uv run --active --no-project pytest


  tests-pypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pypy-version: ["3.10", "3.11", "latest"]
    container:
        image: pypy:${{ matrix.pypy-version }}

    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v10.0.1
      with:
        version: "latest-known"

    - name: Run test suite with pypy
      run: |
        uv venv --python python venv-test
        . venv-test/bin/activate
        uv pip install -e '.[testing]'
        uv run --active --no-project pytest
